
SUPABASE_URL = "https://sxbhizfbgoecmdinriyu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4YmhpemZiZ29lY21kaW5yaXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDU0OTA4ODksImV4cCI6MjAyMTA2Njg4OX0.ixCOmAixD9TrQrr9ncE1LKdQlKPTXTrbOewBdlGCiHU"

[passwords]
# Follow the rule: username = "password"
veronica = "alvin7"
daniel = "alice5"